/**
 * Three DeepSeek AI Agents
 *
 * Agent 1 — CHAT: Client-facing assistant
 *   - Salon info, prices, booking, auth blocks, chat
 *   - Key: DEEPSEEK_API_KEY_CHAT
 *
 * Agent 2 — LANDING: Landing page + SEO generation
 *   - Newsletter landing pages, CMS blocks, SEO metadata
 *   - Key: API_KEY_NEWSLETTER_LANDING_GENERATION
 *
 * Agent 3 — IMAGE: Image prompt generation
 *   - Generates prompts → actual rendering via Google Gemini
 *   - Key: API_KEY_IMAGE_GENERATION
 *   - NOTE: DeepSeek does not support image generation natively.
 *     Image prompts are generated by DeepSeek, then passed to Gemini Imagen.
 */

export type AgentType = "chat" | "landing" | "seo" | "image";

export interface AgentConfig {
  type: AgentType;
  apiKey: string;
  model: string;
  temperature: number;
  maxTokens: number;
  rpmLimit: number;
}

export const AGENTS: Record<AgentType, AgentConfig> = {
  chat: {
    type: "chat",
    apiKey: process.env.DEEPSEEK_API_KEY_CHAT ?? "",
    model: "deepseek-chat",
    temperature: 0.5,
    maxTokens: 2000,
    rpmLimit: 10,
  },
  landing: {
    type: "landing",
    apiKey: process.env.API_KEY_NEWSLETTER_LANDING_GENERATION ?? "",
    model: "deepseek-chat",
    temperature: 0.3,
    maxTokens: 4000,
    rpmLimit: 5,
  },
  image: {
    type: "image",
    // Dedicated DeepSeek key for prompt optimisation.
    // API_KEY_IMAGE_GENERATION is reserved for the OpenAI/DALL-E call in dalle.ts.
    apiKey: process.env.DEEPSEEK_API_KEY_IMAGE ?? process.env.DEEPSEEK_API_KEY_CHAT ?? "",
    model: "deepseek-chat",
    temperature: 0.7,
    maxTokens: 500,
    rpmLimit: 3,
  },
  seo: {
    type: "seo",
    apiKey: process.env.API_KEY_SEO_NEWSLETTER_LANDING_GENERATION ?? "",
    model: "deepseek-chat",
    temperature: 0.3,
    maxTokens: 2000,
    rpmLimit: 5,
  },
};

export const AGENT_PERSONAS = {
  chat: {
    name: "Marysoll",
    role: "Asistent za klijente",
    color: "text-purple-500",
  },
  landing: {
    name: "Maria",
    role: "Specijalista za marketing",
    color: "text-pink-500",
  },
  image: {
    name: "Aria",
    role: "Kreativni asistent",
    color: "text-rose-500",
  },
  seo: {
    name: "SEO",
    role: "Optimizator sadržaja",
    color: "text-blue-500",
  },
};

// ─── DeepSeek API call helper ─────────────────────────────────────────────────

export interface DeepSeekMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

export interface DeepSeekOptions {
  agent: AgentType;
  messages: DeepSeekMessage[];
  stream?: boolean;
  systemPrompt?: string;
  jsonMode?: boolean;
}

export async function callDeepSeek(
  options: DeepSeekOptions,
): Promise<Response> {
  const {
    agent,
    messages,
    stream = false,
    systemPrompt,
    jsonMode = false,
  } = options;
  const config = AGENTS[agent];

  if (!config.apiKey) {
    throw new Error(`DeepSeek API key not configured for agent: ${agent}`);
  }

  const allMessages: DeepSeekMessage[] = systemPrompt
    ? [{ role: "system", content: systemPrompt }, ...messages]
    : messages;

  const response = await fetch("https://api.deepseek.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${config.apiKey}`,
    },
    body: JSON.stringify({
      model: config.model,
      messages: allMessages,
      temperature: config.temperature,
      max_tokens: config.maxTokens,
      stream,
      ...(jsonMode ? { response_format: { type: "json_object" } } : {}),
    }),
  });

  return response;
}
