/**
 * Three DeepSeek AI Agents
 *
 * Agent 1 — CHAT: Client-facing assistant
 *   - Salon info, prices, booking, auth blocks, chat
 *   - Key: DEEPSEEK_API_KEY_CHAT
 *
 * Agent 2 — LANDING: Landing page + SEO generation
 *   - Newsletter landing pages, CMS blocks, SEO metadata
 *   - Key: API_KEY_NEWSLETTER_LANDING_GENERATION
 *
 * Agent 3 — IMAGE: Image prompt generation
 *   - Generates prompts → actual rendering via Google Gemini
 *   - Key: API_KEY_IMAGE_GENERATION
 *   - NOTE: DeepSeek does not support image generation natively.
 *     Image prompts are generated by DeepSeek, then passed to Gemini Imagen.
 */

export type AgentType =
  | "chat"
  | "landing"
  | "seo"
  | "image"
  | "campaignStrategy"
  | "campaignContent"
  | "campaignTemplate"
  | "campaignOptimization"
  | "seoLandingTheme"
  | "metadataSeo"
  | "ctaStrategy"
  | "landingContent";

export interface AgentConfig {
  type: AgentType;
  apiKey: string;
  model: string;
  temperature: number;
  maxTokens: number;
  rpmLimit: number;
}

const AGENTS: Record<AgentType, AgentConfig> = {
  chat: {
    type: "chat",
    apiKey: process.env.DEEPSEEK_API_KEY_CHAT ?? "",
    model: "deepseek-chat",
    temperature: 0.5,
    maxTokens: 2000,
    rpmLimit: 10,
  },
  landing: {
    type: "landing",
    apiKey: process.env.API_KEY_NEWSLETTER_LANDING_GENERATION ?? "",
    model: "deepseek-chat",
    temperature: 0.3,
    maxTokens: 4000,
    rpmLimit: 5,
  },
  image: {
    type: "image",
    apiKey: process.env.API_KEY_OPEN_IMAGE_GEN ?? "",
    model: "gpt-image-1",
    temperature: 0.7,
    maxTokens: 500,
    rpmLimit: 3,
  },
  seo: {
    type: "seo",
    apiKey: process.env.API_KEY_SEO_NEWSLETTER_LANDING_GENERATION ?? "",
    model: "deepseek-chat",
    temperature: 0.3,
    maxTokens: 2000,
    rpmLimit: 5,
  },
  campaignStrategy: {
    type: "campaignStrategy",
    apiKey: process.env.API_KEY_EMAIL_CAMPAIGN_STRATEGY ?? "",
    model: "deepseek-chat",
    temperature: 0.4,
    maxTokens: 2000,
    rpmLimit: 5,
  },
  campaignContent: {
    type: "campaignContent",
    apiKey: process.env.API_KEY_EMAIL_CAMPAIGN_CONTENT ?? "",
    model: "deepseek-chat",
    temperature: 0.6,
    maxTokens: 2500,
    rpmLimit: 5,
  },
  campaignTemplate: {
    type: "campaignTemplate",
    apiKey: process.env.API_KEY_EMAIL_CAMPAIGN_TEMPLATE ?? "",
    model: "deepseek-chat",
    temperature: 0.3,
    maxTokens: 3500,
    rpmLimit: 5,
  },
  campaignOptimization: {
    type: "campaignOptimization",
    apiKey: process.env.API_KEY_EMAIL_CAMPAIGN_OPTIMIZATION ?? "",
    model: "deepseek-chat",
    temperature: 0.2,
    maxTokens: 1500,
    rpmLimit: 5,
  },
  seoLandingTheme: {
    type: "seoLandingTheme",
    apiKey: process.env.API_KEY_SEO_LADNING_THEME ?? "",
    model: "deepseek-chat",
    temperature: 0.2,
    maxTokens: 3000,
    rpmLimit: 5,
  },
  metadataSeo: {
    type: "metadataSeo",
    apiKey: process.env.API_KEY_SEO_METADATA ?? "",
    model: "deepseek-chat",
    temperature: 0.2,
    maxTokens: 3000,
    rpmLimit: 5,
  },
  ctaStrategy: {
    type: "ctaStrategy",
    apiKey: process.env.API_KEY_CTA_STRATEGY ?? "",
    model: "deepseek-chat",
    temperature: 0.25,
    maxTokens: 3000,
    rpmLimit: 5,
  },
  landingContent: {
    type: "landingContent",
    apiKey: process.env.API_KEY_LANDING_CONTENT ?? "",
    model: "deepseek-chat",
    temperature: 0.6,
    // Fix agents (typo-fix / auto-fix) echo the FULL landing structure back as
    // JSON (~13KB+). 8192 is the deepseek-chat max — lower values truncate the
    // output mid-string and cause "Unterminated string in JSON".
    maxTokens: 8192,
    rpmLimit: 3,
  },
};


// ─── DeepSeek API call helper ─────────────────────────────────────────────────

export interface DeepSeekMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

export interface DeepSeekOptions {
  agent: AgentType;
  messages: DeepSeekMessage[];
  stream?: boolean;
  systemPrompt?: string;
  jsonMode?: boolean;
}

export async function callDeepSeek(
  options: DeepSeekOptions,
): Promise<Response> {
  const {
    agent,
    messages,
    stream = false,
    systemPrompt,
    jsonMode = false,
  } = options;
  const config = AGENTS[agent];

  if (!config.apiKey) {
    throw new Error(`DeepSeek API key not configured for agent: ${agent}`);
  }

  const allMessages: DeepSeekMessage[] = systemPrompt
    ? [{ role: "system", content: systemPrompt }, ...messages]
    : messages;

  const response = await fetch("https://api.deepseek.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${config.apiKey}`,
    },
    body: JSON.stringify({
      model: config.model,
      messages: allMessages,
      temperature: config.temperature,
      max_tokens: config.maxTokens,
      stream,
      ...(jsonMode ? { response_format: { type: "json_object" } } : {}),
    }),
  });

  return response;
}
