import { Schema, model, models } from "mongoose";

const NotificationSchema = new Schema(
  {
    tenantId: {
      type: Schema.Types.ObjectId,
      ref: "Tenant",
      required: true,
    },
    recipientProfileId: { type: Schema.Types.ObjectId, ref: "TenantUser", required: true },
    type: {
      type: String,
      enum: [
        "appointment_created",
        "appointment_approved",
        "appointment_rejected",
        "appointment_rescheduled",
        "appointment_cancelled",
        "appointment_message",
        "appointment_reminder",
        "testimonial_created",
        "testimonial_replied",
        "testimonial_updated",
        "testimonial_deleted",
        "testimonial_message",
        "chat_message",
        "tenant_registered",
        "tenant_activated",
        "generic",
        "loyalty_hearts_earned",
        "loyalty_points_earned",
        "loyalty_voucher_received",
        "loyalty_voucher_redeemed",
        "loyalty_tier_upgraded",
        "loyalty_adjustment",
        "loyalty_completion_prompt",
      ],
      required: true,
    },
    title: { type: String, required: true },
    message: { type: String, required: true },
    isRead: { type: Boolean, default: false },
    appointmentId: { type: Schema.Types.ObjectId, ref: "Appointment" },
    testimonialId: { type: Schema.Types.ObjectId, ref: "Testimonial" },
    metadata: {
      oldDate: String,
      oldTime: String,
      newDate: String,
      newTime: String,
      sender: { type: String, enum: ["client", "admin"] },
      clientProfileId: String,
      serviceName: String,
      clientName: String,
      rating: Number,
      // ── Growth Studio (loyalty) ──
      hearts: Number,
      points: Number,
      heartsBalance: Number,
      heartsRequired: Number,
      currencyName: String,
      voucherCode: String,
      voucherType: String,
      voucherValue: Number,
      voucherExpiresAt: String,
      tierName: String,
      // Celebration queue: moment se pušta pri sledećoj poseti panela
      celebration: Boolean,
      celebrationSeen: Boolean,
      _id: false,
    },
  },
  { timestamps: true },
);

export const Notification =
  models.Notification || model("Notification", NotificationSchema);
