import { PlusIcon, TrashIcon, ArrowUpIcon, ArrowDownIcon, ArrowLeftIcon, ArrowRightIcon } from "@heroicons/react/24/outline";
import type { TableBlock } from "@/lib/content/schemas/landing-blocks";
import { createContentBlockId } from "@/lib/content/editor/blockFactories";
import { Field, inputClassName } from "../EditorFields";

function swap<T>(values: T[], index: number, offset: -1 | 1): T[] {
  const target = index + offset;
  if (target < 0 || target >= values.length) return values;
  const next = [...values]; [next[index], next[target]] = [next[target], next[index]]; return next;
}

export function TableBlockEditor({ block, onChange }: { block: TableBlock; onChange: (block: TableBlock) => void }) {
  return <><Field label="Naslov tabele (opciono)" value={block.title ?? ""} onChange={(title) => onChange({ ...block, title })} /><Field label="Opis tabele (opciono)" value={block.caption ?? ""} onChange={(caption) => onChange({ ...block, caption })} />
    <div className="space-y-2"><p className="text-xs font-semibold uppercase text-gray-500">Kolone</p>{block.columns.map((column, index) => <div key={column.id} className="flex items-center gap-1"><input aria-label={`Kolona ${index + 1}`} className={inputClassName} value={column.label} onChange={(event) => onChange({ ...block, columns: block.columns.map((current) => current.id === column.id ? { ...current, label: event.target.value } : current) })} /><button type="button" aria-label="Pomeri kolonu levo" disabled={index === 0} onClick={() => onChange({ ...block, columns: swap(block.columns, index, -1) })}><ArrowLeftIcon className="h-4 w-4" /></button><button type="button" aria-label="Pomeri kolonu desno" disabled={index === block.columns.length - 1} onClick={() => onChange({ ...block, columns: swap(block.columns, index, 1) })}><ArrowRightIcon className="h-4 w-4" /></button><button type="button" aria-label="Obriši kolonu" className="text-red-600" onClick={() => onChange({ ...block, columns: block.columns.filter(({ id }) => id !== column.id), rows: block.rows.map((row) => { const cells = { ...row.cells }; delete cells[column.id]; return { ...row, cells }; }) })}><TrashIcon className="h-4 w-4" /></button></div>)}<button type="button" className="inline-flex items-center gap-1 rounded border px-3 py-2 text-xs font-semibold" onClick={() => { const id = createContentBlockId(); onChange({ ...block, columns: [...block.columns, { id, label: "" }], rows: block.rows.map((row) => ({ ...row, cells: { ...row.cells, [id]: "" } })) }); }}><PlusIcon className="h-4 w-4" /> Dodaj kolonu</button></div>
    <div className="space-y-3"><p className="text-xs font-semibold uppercase text-gray-500">Redovi</p>{block.rows.map((row, rowIndex) => <div key={row.id} className="space-y-2 rounded border p-2"><div className="flex justify-end gap-2"><button type="button" aria-label="Pomeri red gore" disabled={rowIndex === 0} onClick={() => onChange({ ...block, rows: swap(block.rows, rowIndex, -1) })}><ArrowUpIcon className="h-4 w-4" /></button><button type="button" aria-label="Pomeri red dole" disabled={rowIndex === block.rows.length - 1} onClick={() => onChange({ ...block, rows: swap(block.rows, rowIndex, 1) })}><ArrowDownIcon className="h-4 w-4" /></button><button type="button" aria-label="Obriši red" className="text-red-600" onClick={() => onChange({ ...block, rows: block.rows.filter(({ id }) => id !== row.id) })}><TrashIcon className="h-4 w-4" /></button></div>{block.columns.map((column) => <Field key={column.id} label={column.label || "Neimenovana kolona"} value={row.cells[column.id] ?? ""} onChange={(value) => onChange({ ...block, rows: block.rows.map((current) => current.id === row.id ? { ...current, cells: { ...current.cells, [column.id]: value } } : current) })} />)}</div>)}<button type="button" disabled={block.columns.length === 0} className="inline-flex items-center gap-1 rounded border px-3 py-2 text-xs font-semibold disabled:opacity-50" onClick={() => onChange({ ...block, rows: [...block.rows, { id: createContentBlockId(), cells: Object.fromEntries(block.columns.map(({ id }) => [id, ""])) }] })}><PlusIcon className="h-4 w-4" /> Dodaj red</button></div>
  </>;
}
